<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<title></title>
</head>
<body>
<table border="1px">
	<tr>
		<td style="color: red;"> primera pagina </td>
	</tr>
</table>
<table border="1px">
	<tr>
		<td>
			<nav>
				<ul>
					<li><a href="">inicio</a></li>
					<li><a href="">nosotros</a></li>
				</ul>
			</nav>
		</td>
	</tr>
</table>
<table border="1px">
	<tr>
		<td>
			<?php
			 $base=10;
			 $altura=5;
			
			 print "area del triangulo:".($base*$altura)/2;
			 

			?>

		</td>
	</tr>
	
</table>



</body>
</html>